app = "grape-baby"
primary_region = "nrt"

[build]

[env]
  DATABASE_URL = "file:/data/grape.db"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[mounts]
  source = "grape_data"
  destination = "/data"
